version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    reviewers:
      - snout-router/dependabot-reviewers
  - package-ecosystem: terraform
    directory: /
    schedule:
      interval: weekly
    reviewers:
      - snout-router/dependabot-reviewers
