name: Terraform
on:
  push:
    branches:
    - '*'
  pull_request:
jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: Check formatting
        run: terraform fmt -check
      - name: Initialize
        run: terraform init
      - name: Validate
        run: terraform validate
      - name: Plan
        if: github.event_name == 'pull_request'
        run: terraform plan -input=false
      - name: Apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve -input=false
